name: 'Release Drafter'

on:
  push:
    branches:
      - main
      - master

jobs:
  update_release_draft:
    name: Release
    uses: chukysoria/workflows/.github/workflows/new-release.yml@e6782c2fc4a5c686a4f937ef850ca3860c712ea4 # v1.1.10
