---
   
name: Sync labels
            
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:
                                                                                            
                                                                                                  
jobs:
  labels:
    name: ♻️ Sync labels
    uses: chukysoria/workflows/.github/workflows/labels.yml@e6782c2fc4a5c686a4f937ef850ca3860c712ea4 # v1.1.10
                                                                                                                            
